spring:
  sql:
    init:
      schema-locations:
        - classpath:sql/ddl/first/*
        - classpath:sql/ddl/second/*
        - classpath:sql/ddl/third/*

      continue-on-error: true
      mode: always
      platform: h2
      data-locations:
        - classpath:sql/dml/first/*
        - classpath:sql/dml/second/*
        - classpath:sql/dml/third/*
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password: password
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

springdoc:
  version: '0.0'
  swagger-ui:
    path: /openapi