spring:
  sql:
    init:
      schema-locations:
        - classpath:sql/ddl/first/*
        - classpath:sql/ddl/second/*
        - classpath:sql/ddl/third/*

      continue-on-error: true
      mode: always
      platform: h2
      data-locations:
        - classpath:sql/dml/first/*
        - classpath:sql/dml/second/*
        - classpath:sql/dml/third/*
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    database: h2
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password: password
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

springdoc:
  version: '0.0'
  swagger-ui:
    path: /openapi

feign:
  httpclient:
    max-connections: 300
    max-connections-per-route: 300
  circuitbreaker:
    enabled: true
  autoconfiguration:
    jackson:
      enabled: true
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000
      exampleClient:
        connect-timeout: 4000
        read-timeout: 4000
        url: "http://localhost:8081"
      messageClient:
        connect-timeout: 400
        read-timeout: 400
        url: "http://localhost:8081"

    default-to-properties: false
