create table ITEM
(
    DTYPE    CHARACTER VARYING(31) NOT NULL ,
    ITEM_ID  BIGINT NOT NULL AUTO_INCREMENT,
    NAME     CHARACTER VARYING(255),
    PRICE    INTEGER  NOT NULL ,
    ARTIST   VARCHAR(255),
    AUTHOR   VARCHAR(255),
    ACTOR    VARCHAR(255),
    DIRECTOR VARCHAR(255),
    PRIMARY KEY (ITEM_ID)
);
